#! /bin/sh


$HOME/.config/polybar/launch.sh&
$HOME/.config/bspwm/syncpad.sh&


bspc monitor -d code term game media

bspc config border_width         5
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

